apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: devhub:apps/Deployment:default/devhub-deployment
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"devhub:apps/Deployment:default/devhub-deployment"},"labels":{"app":"devhub-app"},"name":"devhub-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"devhub-app"}},"template":{"metadata":{"labels":{"app":"devhub-app"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","valueFrom":{"configMapKeyRef":{"key":"DB_HOST","name":"devhub-config"}}},{"name":"DB_PORT","valueFrom":{"configMapKeyRef":{"key":"DB_PORT","name":"devhub-config"}}},{"name":"SERVER_PORT","valueFrom":{"configMapKeyRef":{"key":"SERVER_PORT","name":"devhub-config"}}},{"name":"DB_NAME","valueFrom":{"secretKeyRef":{"key":"DB_NAME","name":"devhub-secrets"}}},{"name":"DB_USER","valueFrom":{"secretKeyRef":{"key":"DB_USER","name":"devhub-secrets"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"DB_PASSWORD","name":"devhub-secrets"}}}],"image":"kartavyanirwel/devhub-app:v1.0","livenessProbe":{"httpGet":{"path":"/","port":8080},"initialDelaySeconds":60,"periodSeconds":15},"name":"devhub-app","ports":[{"containerPort":8080}],"readinessProbe":{"httpGet":{"path":"/","port":8080},"initialDelaySeconds":30,"periodSeconds":10},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2026-06-06T08:17:11Z"
  generation: 3
  labels:
    app: devhub-app
  name: devhub-deployment
  namespace: default
  resourceVersion: "2833"
  uid: b6b50200-47a5-45ef-b617-a88a65f8cfb6
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: devhub-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devhub-app
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: devhub-config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: devhub-config
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: SERVER_PORT
              name: devhub-config
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: devhub-secrets
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: devhub-secrets
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: devhub-secrets
        image: kartavyanirwel/devhub-app:v1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: devhub-app
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2026-06-06T08:17:11Z"
    lastUpdateTime: "2026-06-06T08:17:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-06-06T08:17:11Z"
    lastUpdateTime: "2026-06-06T08:18:50Z"
    message: ReplicaSet "devhub-deployment-bcdb7b5fb" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 3
  replicas: 2
  terminatingReplicas: 0
  unavailableReplicas: 2
  updatedReplicas: 2
