# ============================================================
#  DevHub - MySQL PersistentVolume + PersistentVolumeClaim
#  Data pod restart ke baad bhi survive karega
# ============================================================

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce          # Ek time pe ek node hi read/write karega
  persistentVolumeReclaimPolicy: Retain   # Pod delete ho toh data mat delete karo
  hostPath:
    path: /mnt/data/mysql    # Minikube node pe yeh path pe data store hoga

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi           # PV se 1Gi maang raha hai

---
# ============================================================
#  DevHub - MySQL Deployment
# ============================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devhub-mysql
  namespace: default
  labels:
    app: devhub-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devhub-mysql
  template:
    metadata:
      labels:
        app: devhub-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: devhub-secrets
              key: DB_NAME
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devhub-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: devhub-secrets
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devhub-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql    # MySQL yahan data store karta hai
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc         # emptyDir ki jagah PVC use ho raha hai

---
# ============================================================
#  DevHub - MySQL Service
# ============================================================

apiVersion: v1
kind: Service
metadata:
  name: devhub-mysql-service
  namespace: default
spec:
  selector:
    app: devhub-mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
