apiVersion: apps/v1
kind: Deployment
metadata:
  name: devhub-mysql
  namespace: default
  labels:
    app: devhub-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devhub-mysql
  template:
    metadata:
      labels:
        app: devhub-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: devhub-secrets
              key: DB_NAME

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devhub-secrets
              key: MYSQL_ROOT_PASSWORD

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: devhub-mysql-service
  namespace: default
spec:
  selector:
    app: devhub-mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP