apiVersion: v1
kind: Secret
metadata:
  name: devhub-secrets
  namespace: default
type: Opaque
data:
  DB_NAME: ZGV2aHViX2Ri
  DB_USER: ZGV2aHViX3VzZXI=
  DB_PASSWORD: ZGV2aHViX3Bhc3M=
  MYSQL_ROOT_PASSWORD: cm9vdF9zZWN1cmVfcGFzc3dvcmQ=
