apiVersion: v1
kind: Secret
metadata:
  name: devhub-secrets
type: Opaque
data:
  DB_NAME: <BASE64_DB_NAME>
  DB_USER: <BASE64_DB_USER>
  DB_PASSWORD: <BASE64_DB_PASSWORD>
  MYSQL_ROOT_PASSWORD: <BASE64_ROOT_PASSWORD>
