apiVersion: v1
kind: Secret
metadata:
  name: devhub-secrets
type: Opaque
data:
  DB_USER: cm9vdA==

  # root_secure_password
  DB_PASSWORD: cm9vdF9zZWN1cmVfcGFzc3dvcmQ=

  MYSQL_ROOT_PASSWORD: cm9vdF9zZWN1cmVfcGFzc3dvcmQ=

  DB_NAME: ZGV2aHViX2Ri
